files:
  include:
    - 'src/styles/**/*.scss'
    - 'src/styles/*.scss'
  ignore:
    - 'src/styles/settings/*.scss.liquid'
    - 'src/styles/vendor/**/*.scss'
    - 'src/styles/vendor/*.scss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero: 1
  brace-style:
    - 1
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: hyphenatedbem
  clean-import-paths: 1
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: false
  extends-before-declarations: 0
  extends-before-mixins: 0
  final-newline: 1
  function-name-format: 1
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  id-name-format:
    - 1
    - convention: hyphenatedbem
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 1
    - include: true
  mixin-name-format: 1
  mixins-before-declarations: 0
  nesting-depth: 0
  no-color-literals: 1
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 0
  no-empty-rulesets: 1
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    - extra-properties:
        - mso-table-lspace
        - mso-table-rspace
  no-qualifying-elements: 0
  no-trailing-zero: 1
  no-url-protocols: 1
  no-vendor-prefixes:
    - 0
    - excluded-identifiers:
        - selection
  placeholder-in-extend: 0
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order: 0
  quotes: 0
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-colon:
    - 1
    - include: true
  space-after-comma: 1
  space-before-brace: 1
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 1
  variable-name-format: 1
  zero-unit: 1
