---
# Theme Kit - http://themekit.cat
# Get your api_key and password at your-url.myshopify.com/admin/apps/private
# Copy this file and rename it config.yml

development:
  access_token:
  store: your-url.myshopify.com
  theme_id:
  ignore_files:
    # - Relative to the dist/ folder
