---
# Theme gem usage - https://github.com/Shopify/shopify_theme
# Get your api_key and password at your-url.myshopify.com/admin/apps/private

:api_key:
:password:
:store: your-url.myshopify.com
:theme_id:
:ignore_files:
  - node_modules/
  - src/
  # - settings_data.json
  # - logo.png
