version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-cache-{{ checksum "package.json" }}
            - v1-yarn-cache
      - run:
          name: Bootstrap packages
          command: yarn run bootstrap
      - run:
          name: Test packages
          command: yarn test
      - save-cache:
          key: v1-yarn-cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - save-cache:
          key: v1-yarn-cache
          paths:
            - ~/.cache/yarn
workflows:
  version: 2
  test:
      jobs:
        - test:
            filters:
              tags:
                only: /.*/

